spring:
  application:
    name: "example-spring-boot"
  ### MySQL 连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: "jdbc:mysql://192.168.1.11:3306/example-spring-boot?serverTimezone=UTC"
    username: username
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080
debug: on
