<!doctype html>
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
        <meta name="App-Config" content="fullscreen=yes,useHistoryState=yes,transition=yes">
        <meta content="yes" name="apple-mobile-web-app-capable">
        <meta content="yes" name="apple-touch-fullscreen">
        <meta content="telephone=no,email=no" name="format-detection">
        <title>将进酒</title>
        <link rel="apple-touch-icon-precomposed" sizes="57x57"
              href="//gw.alicdn.com/tps/i2/TB1nmqyFFXXXXcQbFXXE5jB3XXX-114-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72"
              href="//gw.alicdn.com/tps/i2/TB1nmqyFFXXXXcQbFXXE5jB3XXX-114-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114"
              href="//gw.alicdn.com/tps/i2/TB1nmqyFFXXXXcQbFXXE5jB3XXX-114-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144"
              href="//gw.alicdn.com/tps/i2/TB1nmqyFFXXXXcQbFXXE5jB3XXX-114-114.png">
        <link rel="Shortcut Icon" type="image/x-icon"
              href="//gw.alicdn.com/tps/i2/TB1nmqyFFXXXXcQbFXXE5jB3XXX-114-114.png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
              integrity="sha256-l85OmPOjvil/SOvVt3HnSSjzF1TUMyT9eV0c2BzEGzU=" crossorigin="anonymous"/>
        <link rel="stylesheet" href="/css/base.css">
    </head>
    <body>
        <div>
            <h1>将进酒</h1>
            <p>君不见，黄河之水天上来，奔流到海不复回。 <br>
                君不见，高堂明镜悲白发，朝如青丝暮成雪。 <br>
                人生得意须尽欢，莫使金樽空对月。 <br>
                天生我才必有用，千金散尽还复来。 <br>
                烹羊宰牛且为乐，会须一饮三百杯。 <br>
                岑夫子，丹丘生，将进酒，杯莫停。 <br>
                与君歌一曲，请君为我倾耳听。 <br>
                钟鼓馔玉不足贵，但愿长醉不复醒。 <br>
                古来圣贤皆寂寞，惟有饮者留其名。 <br>
                陈王昔时宴平乐，斗酒十千恣欢谑。 <br>
                主人何为言少钱，径须沽取对君酌。 <br>
                五花马，千金裘，呼儿将出换美酒，与尔同销万古愁。
            </p>
        </div>
    </body>
</html>